"use strict";

// 공격 중심 탄환 효과 V1
// stats: direct, fire, frost, wind, shield, split, pierce, explode, multicast
// shot: straight | homing | null. 총 카드는 크기별 개별 탄약을 사용한다.
const CARD_CATALOG = [
  { id: "dagger", name: "단검", emoji: "🗡️", size: 1, cost: 2, cooldown: 4.8, tags: ["무기"], shot: "straight", stats: { direct: [6, 2] }, desc: "직선으로 날아가는 기본 탄환입니다." },
  { id: "fire_sword", name: "화염검", emoji: "🔥", size: 1, cost: 2, cooldown: 5.8, tags: ["무기"], shot: "homing", stats: { direct: [5, 1], fire: [1, 1] }, desc: "유도 화염탄으로 지속 피해를 남깁니다." },
  { id: "frost_bow", name: "냉기궁", emoji: "❄️", size: 1, cost: 2, cooldown: 6.2, tags: ["무기"], shot: "homing", stats: { direct: [4, 1], frost: [1, 1] }, desc: "유도 냉기탄으로 적의 이동과 공격을 늦춥니다." },
  { id: "wind_sprite", name: "보급 정령", emoji: "💨", size: 1, cost: 2, cooldown: 5.5, tags: ["사역마"], shot: "homing", reload: 1, stats: { direct: [2, 1], wind: [1, 1] }, desc: "발동 시 인접한 총 한 자루에 탄약을 장전하고 바람을 부여합니다." },
  { id: "shield_sprite", name: "방벽 정령", emoji: "🛡️", size: 1, cost: 2, cooldown: 7, tags: ["사역마"], shot: null, stats: { shield: [9, 4] }, desc: "성벽에 즉시 보호막을 부여합니다." },
  { id: "fire_gun", name: "화염총", emoji: "🔫", size: 1, cost: 2, cooldown: 5.8, tags: ["총"], shot: "homing", stats: { direct: [8, 2], fire: [2, 1] }, desc: "탄약을 소모해 강한 유도 화염탄을 발사합니다." },
  { id: "frost_gun", name: "빙결총", emoji: "🔫", size: 1, cost: 2, cooldown: 6.2, tags: ["총"], shot: "straight", stats: { direct: [8, 2], frost: [2, 1] }, desc: "탄약을 소모해 직선 냉기탄을 발사합니다." },
  { id: "spark_gun", name: "신호총", emoji: "✨", size: 1, cost: 2, cooldown: 5.2, tags: ["총"], shot: "homing", stats: { direct: [10, 2] }, desc: "빠른 유도탄을 발사하는 기본 총입니다." },

  { id: "scatter_cannon", name: "산탄포", emoji: "💥", size: 2, cost: 3, cooldown: 7.4, tags: ["총"], shot: "straight", stats: { direct: [8, 2], split: [3, 0] }, desc: "최대 세 적에게 산탄을 나누고, 남는 탄환은 주 대상에게 감쇠 피해를 줍니다." },
  { id: "pierce_rifle", name: "관통 소총", emoji: "🏹", size: 2, cost: 3, cooldown: 7.2, tags: ["무기"], shot: "straight", stats: { direct: [10, 3], pierce: [3, 1] }, desc: "예상 관통 수가 많은 세로 또는 사선 궤적을 조준합니다." },
  { id: "bomb_launcher", name: "폭발 발사기", emoji: "🚀", size: 2, cost: 3, cooldown: 8.3, tags: ["총"], shot: "homing", stats: { direct: [9, 2], explode: [1, 1] }, desc: "첫 적 명중 후 주변 공중 적에게 범위 피해를 줍니다." },
  { id: "wind_eagle", name: "바람 독수리", emoji: "🦅", size: 2, cost: 3, cooldown: 7.2, tags: ["사역마"], shot: "homing", reload: 1, stats: { direct: [5, 2], wind: [2, 1] }, desc: "인접 총을 우선 장전하고 인접 카드에 바람을 부여합니다." },
  { id: "shield_tower", name: "방벽 장치", emoji: "🔷", size: 2, cost: 3, cooldown: 8.5, tags: ["사역마"], shot: null, stats: { shield: [16, 7] }, desc: "큰 보호막으로 성벽을 지킵니다." },
  { id: "flame_hydra", name: "화염 히드라", emoji: "🐍", size: 2, cost: 3, cooldown: 8.1, tags: ["무기", "사역마"], shot: "homing", stats: { direct: [7, 3], fire: [2, 1], split: [2, 1] }, desc: "여러 적에게 유도 화염탄을 나누어 발사합니다." },
  { id: "frost_ray", name: "빙결 광선기", emoji: "🧊", size: 2, cost: 3, cooldown: 7.8, tags: ["무기"], shot: "straight", stats: { direct: [8, 2], frost: [2, 1], pierce: [2, 1] }, desc: "관통 냉기탄으로 적 무리를 늦춥니다." },
  { id: "burst_gun", name: "연발총", emoji: "🔫", size: 2, cost: 3, cooldown: 7, tags: ["총"], shot: "homing", stats: { direct: [8, 2], split: [2, 0] }, desc: "유도탄 두 발을 나누어 쏘며, 적이 하나면 두 번째 탄환은 감쇠 피해를 줍니다." },
  { id: "supply_orb", name: "탄약 구체", emoji: "📦", size: 2, cost: 3, cooldown: 6.8, tags: ["사역마"], shot: null, reload: 1, stats: { wind: [1, 1], shield: [5, 3] }, desc: "발동 시 탄약이 가장 적은 인접 총을 장전합니다." },

  { id: "flame_lord", name: "화염 군주", emoji: "👾", size: 3, cost: 5, cooldown: 9.5, tags: ["무기", "사역마"], shot: "homing", stats: { direct: [14, 4], fire: [3, 0.5], multicast: [1, 1] }, desc: "시간차 유도 화염탄을 반복 발사합니다." },
  { id: "storm_lord", name: "폭풍 군주", emoji: "🌪️", size: 3, cost: 5, cooldown: 9.5, tags: ["사역마"], shot: "homing", reload: 1, stats: { direct: [8, 3], wind: [3, 1], multicast: [1, 1] }, desc: "인접 총을 장전하고 전장에 바람을 퍼뜨립니다." },
  { id: "siege_gun", name: "공성포", emoji: "🧨", size: 3, cost: 5, cooldown: 10, tags: ["총"], shot: "straight", stats: { direct: [16, 5], pierce: [4, 1] }, desc: "강한 직선 관통탄으로 긴 사선을 지배합니다." },
  { id: "bombard_gun", name: "융단포", emoji: "🎇", size: 3, cost: 5, cooldown: 10.5, tags: ["총"], shot: "homing", stats: { direct: [14, 4], explode: [2, 1], multicast: [1, 1] }, desc: "반복 폭발탄으로 적 무리를 정리합니다." },
  { id: "mirror_cannon", name: "분열 포대", emoji: "⚡", size: 3, cost: 5, cooldown: 10, tags: ["무기"], shot: "homing", stats: { direct: [12, 4], split: [3, 0], multicast: [1, 1] }, desc: "여러 유도탄을 시간차로 연속 발사합니다." },
  { id: "frost_lord", name: "서리 군주", emoji: "☃️", size: 3, cost: 5, cooldown: 10, tags: ["무기", "사역마"], shot: "straight", stats: { direct: [13, 4], frost: [3, 0.5], pierce: [3, 1] }, desc: "관통 냉기탄으로 적 무리의 접근을 늦춥니다." },
];

// 적 데이터는 플레이어 카드 효과와 분리한다. 전투에 필요한 기본 전투력만 가진다.
const MONSTER_CARD_CATALOG = [
  { id: "slime_점액탄", family: "슬라임", name: "점액탄", emoji: "🫧", size: 1, cooldown: 5, stats: { direct: [5, 0] } },
  { id: "slime_끈적한발톱", family: "슬라임", name: "끈적한 발톱", emoji: "🐾", size: 1, cooldown: 5, stats: { direct: [6, 0] } },
  { id: "slime_점액구체", family: "슬라임", name: "점액 구체", emoji: "🟢", size: 2, cooldown: 6, stats: { direct: [8, 0] } },
  { id: "slime_분열슬라임", family: "슬라임", name: "분열 슬라임", emoji: "🟢", size: 2, cooldown: 7, stats: { direct: [9, 0] } },
  { id: "slime_대형점액탄", family: "슬라임", name: "대형 점액탄", emoji: "🟦", size: 3, cooldown: 9, stats: { direct: [13, 0] } },
  { id: "goblin_단검투척", family: "고블린", name: "단검 투척", emoji: "🔪", size: 1, cooldown: 5, stats: { direct: [6, 0] } },
  { id: "goblin_독침", family: "고블린", name: "독침", emoji: "🪡", size: 1, cooldown: 5, stats: { direct: [7, 0] } },
  { id: "goblin_약탈단검", family: "고블린", name: "약탈 단검", emoji: "🥷", size: 2, cooldown: 7, stats: { direct: [10, 0] } },
  { id: "goblin_화약탄", family: "고블린", name: "화약탄", emoji: "🎆", size: 2, cooldown: 7, stats: { direct: [11, 0] } },
  { id: "goblin_약탈자의검", family: "고블린", name: "약탈자의 검", emoji: "🏴‍☠️", size: 3, cooldown: 10, stats: { direct: [15, 0] } },
  { id: "orc_전투도끼", family: "오크", name: "전투 도끼", emoji: "🪓", size: 1, cooldown: 5, stats: { direct: [7, 0] } },
  { id: "orc_화약방패", family: "오크", name: "화약 방패", emoji: "💥", size: 1, cooldown: 5.5, stats: { direct: [7, 0], shield: [8, 0] } },
  { id: "orc_전쟁도끼", family: "오크", name: "전쟁 도끼", emoji: "🪚", size: 2, cooldown: 7.5, stats: { direct: [12, 0] } },
  { id: "orc_강철방패", family: "오크", name: "강철 방패", emoji: "🪢", size: 2, cooldown: 7, stats: { direct: [9, 0], shield: [12, 0] } },
  { id: "orc_오크파괴자", family: "오크", name: "오크 파괴자", emoji: "🏕️", size: 3, cooldown: 10.5, stats: { direct: [17, 0] } },
  { id: "vamp_흡혈박쥐", family: "뱀파이어", name: "흡혈 박쥐", emoji: "🌑", size: 1, cooldown: 5, stats: { direct: [7, 0] } },
  { id: "vamp_뱀파이어송곳니", family: "뱀파이어", name: "뱀파이어 송곳니", emoji: "🦷", size: 1, cooldown: 5, stats: { direct: [8, 0] } },
  { id: "vamp_피의채찍", family: "뱀파이어", name: "피의 채찍", emoji: "〰️", size: 2, cooldown: 7, stats: { direct: [11, 0] } },
  { id: "vamp_흡혈군주", family: "뱀파이어", name: "흡혈 군주", emoji: "🧛", size: 2, cooldown: 7, stats: { direct: [12, 0], shield: [10, 0] } },
  { id: "vamp_피의왕좌", family: "뱀파이어", name: "피의 왕좌", emoji: "🪑", size: 3, cooldown: 10, stats: { direct: [18, 0], shield: [14, 0] } },
  { id: "drake_화염비늘", family: "드레이크", name: "화염 비늘", emoji: "🛡️", size: 1, cooldown: 5, stats: { direct: [7, 0] } },
  { id: "drake_용의발톱", family: "드레이크", name: "용의 발톱", emoji: "🐉", size: 1, cooldown: 5, stats: { direct: [8, 0] } },
  { id: "drake_용염", family: "드레이크", name: "용염", emoji: "♨️", size: 2, cooldown: 7, stats: { direct: [12, 0] } },
  { id: "drake_드래곤불꽃", family: "드레이크", name: "드래곤 불꽃", emoji: "🐲", size: 2, cooldown: 7, stats: { direct: [13, 0] } },
  { id: "drake_용의숨결", family: "드레이크", name: "용의 숨결", emoji: "🌬️", size: 3, cooldown: 10, stats: { direct: [19, 0] } },
  { id: "spider_독실거미", family: "거미여왕", name: "독실 거미", emoji: "🦂", size: 1, cooldown: 5, stats: { direct: [7, 0] } },
  { id: "spider_거미송곳", family: "거미여왕", name: "거미 송곳", emoji: "🧵", size: 1, cooldown: 5.5, stats: { direct: [8, 0] } },
  { id: "spider_독거미줄", family: "거미여왕", name: "독 거미줄", emoji: "🧶", size: 2, cooldown: 7, stats: { direct: [11, 0] } },
  { id: "spider_거미군단", family: "거미여왕", name: "거미 군단", emoji: "🐜", size: 2, cooldown: 7, stats: { direct: [12, 0] } },
  { id: "spider_여왕의거미집", family: "거미여왕", name: "여왕의 거미집", emoji: "🏚️", size: 3, cooldown: 10, stats: { direct: [18, 0] } },
  { id: "water_물방울정령", family: "물의 정령", name: "물방울 정령", emoji: "💦", size: 1, cooldown: 5, stats: { direct: [8, 0] } },
  { id: "water_물결채찍", family: "물의 정령", name: "물결 채찍", emoji: "🔵", size: 1, cooldown: 5, stats: { direct: [8, 0] } },
  { id: "water_파도사역마", family: "물의 정령", name: "파도 정령", emoji: "🐬", size: 2, cooldown: 7, stats: { direct: [13, 0] } },
  { id: "water_물의제단", family: "물의 정령", name: "물의 제단", emoji: "⛲", size: 2, cooldown: 9, stats: { direct: [11, 0], shield: [12, 0] } },
  { id: "water_해일", family: "물의 정령", name: "해일", emoji: "🌀", size: 3, cooldown: 10, stats: { direct: [20, 0] } },
  { id: "maou_마왕의손가락", family: "마왕", name: "마왕의 손가락", emoji: "☝️", size: 1, cooldown: 5, stats: { direct: [9, 0] } },
  { id: "maou_절망의칼날", family: "마왕", name: "절망의 칼날", emoji: "⚰️", size: 1, cooldown: 5, stats: { direct: [10, 0] } },
  { id: "maou_마왕의불꽃", family: "마왕", name: "마왕의 불꽃", emoji: "☄️", size: 2, cooldown: 7, stats: { direct: [15, 0] } },
  { id: "maou_마왕의저주", family: "마왕", name: "마왕의 저주", emoji: "💀", size: 2, cooldown: 9, stats: { direct: [16, 0] } },
  { id: "maou_마왕의검", family: "마왕", name: "마왕", emoji: "👑", size: 3, cooldown: 12, stats: { direct: [28, 0], shield: [25, 0] } },
];
